'use strict';function y(k,a,b,d){k.v.kc(k.Wa,a,b,d,void 0)}function E(k,a,b,d){k.v.ra?y(k,a,b,d):k.v.cf()._OnMessageFromDOM({type:"event",component:k.Wa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function G(k,a,b){k.v.B(k.Wa,a,b)}function I(k,a){for(const [b,d]of a)G(k,b,d)}function J(k){k.Nb||(k.v.Oe(k.Yd),k.Nb=!0)}window.sb=class{constructor(k,a){this.v=k;this.Wa=a;this.Nb=!1;this.Yd=()=>this.Da()}ad(){}Da(){}};function K(k){-1!==k.Oa&&(self.clearTimeout(k.Oa),k.Oa=-1)}
window.Fe=class{constructor(k,a){this.Ic=k;this.qg=a;this.Oa=-1;this.Ob=-Infinity;this.Zd=()=>{this.Oa=-1;this.Ob=Date.now();this.ab=!0;this.Ic();this.ab=!1};this.Hd=this.ab=!1}c(){K(this);this.Zd=this.Ic=null}};"use strict";function L(k,a){G(k,"get-element",b=>{const d=k.ca.get(b.elementId);return a(d,b)})}
window.Jg=class extends self.sb{constructor(k,a){super(k,a);this.ca=new Map;this.Hc=!0;I(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Hc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Hc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Hc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>{{const d=this.ca.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);L(this,b=>b)}};"use strict";
{const k=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h,c){const g=document.createElement("script");g.async=!1;"module"===c&&(g.type="module");return h.Ag?new Promise(l=>{const n="c3_resolve_"+a;++a;self[n]=l;g.textContent=h.Dg+`\n\nself["${n}"]();`;document.head.appendChild(g)}):new Promise((l,n)=>{g.onload=l;g.onerror=n;g.src=h;document.head.appendChild(g)})}let d=!1,f=!1;function m(){if(!d){try{new Worker("blob://",{get type(){f=!0}})}catch(h){}d=
!0}return f}let p=new Audio;const v={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await B(h);return(new TextDecoder("utf-8")).decode(h)}function B(h){return new Promise((c,
g)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>g(n);l.readAsArrayBuffer(h)})}const u=[];let w=0;window.RealFile=window.File;const C=[],x=new Map,D=new Map;let F=0;const H=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");H.push(h)};const e=new Set(["cordova","playable-ad","instant-games"]);window.xb=class h{constructor(c){this.ra=c.Fg;this.pa=null;this.D="";this.Wb=c.Cg;this.da=c.be;this.pb={};this.Ha=this.ob=null;
this.Lb=[];this.cb=this.J=this.Ma=null;this.La=-1;this.vg=()=>this.Cf();this.Ka=[];this.L=c.$d;!this.ra||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.da||m())||(this.ra=!1);e.has(this.L)&&this.ra&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.ra=!1);this.Qb=this.ia=null;"html5"!==this.L&&"playable-ad"!==this.L||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.B("runtime","cordova-fetch-local-file",g=>this.lf(g));this.B("runtime","create-job-worker",()=>this.mf());"cordova"===this.L?document.addEventListener("deviceready",()=>this.td(c)):this.td(c)}c(){this.qc();this.pa&&(this.pa=this.pa.onmessage=null);this.ob&&(this.ob.terminate(),this.ob=null);this.Ha&&(this.Ha.c(),this.Ha=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}jd(){return k&&"cordova"===this.L}jc(){return k&&e.has(this.L)||navigator.standalone}async td(c){if("playable-ad"===
this.L){this.ia=self.c3_base64files;this.Qb={};await this.Te();for(let l=0,n=c.Pa.length;l<n;++l){var g=c.Pa[l].toLowerCase();this.Qb.hasOwnProperty(g)?c.Pa[l]={Ag:!0,Dg:this.Qb[g]}:this.ia.hasOwnProperty(g)&&(c.Pa[l]=URL.createObjectURL(this.ia[g]))}}c.wg?this.D=c.wg:(g=location.origin,this.D=("null"===g?"file:///":g)+location.pathname,g=this.D.lastIndexOf("/"),-1!==g&&(this.D=this.D.substr(0,g+1)));c.Hg&&(this.pb=c.Hg);g=new MessageChannel;this.pa=g.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.yf(l));this.cb=new self.Be(this);await M(this.cb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ra?await this.ef(c,g.port2):await this.df(c,g.port2)}tc(c){c=this.pb.hasOwnProperty(c)?this.pb[c]:c.endsWith("/workermain.js")&&this.pb.hasOwnProperty("workermain.js")?this.pb["workermain.js"]:"playable-ad"===this.L&&this.ia.hasOwnProperty(c.toLowerCase())?
this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async bc(c,g,l){if(c.startsWith("blob:"))return new Worker(c,l);if(this.jd()&&"file:"===location.protocol)return c=await this.rb(this.Wb+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,g);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,
l)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}sd(c){var g=this.cb;return{baseUrl:this.D,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.ic(),projectData:c.Ng,scriptsType:c.be,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Lg||"",exportType:c.$d,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.Mg,jobScheduler:{inputPort:g.Oc,outputPort:g.Vc,maxNumWorkers:g.sg},supportedAudioFormats:v,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Wb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Wb+"opus.wasm.wasm",isiOSCordova:this.jd(),isiOSWebView:this.jc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ef(c,g){var l=this.tc(c.Gg);this.ob=await this.bc(l,this.D,{type:this.da,name:"Runtime"});this.J=document.createElement("canvas");this.J.style.display=
"none";l=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;this.ob.postMessage(Object.assign(this.sd(c),{type:"init-runtime",isInWorker:!0,messagePort:g,canvas:l,workerDependencyScripts:c.$c||[],engineScripts:c.Pa,projectScripts:c.qb,mainProjectScript:c.ae,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[g,l,...N(this.cb)]);this.Lb=C.map(n=>new n(this));this.rd();self.c3_callFunction=(n,q)=>this.Ma.ff(n,q);"preview"===this.L&&(self.goToLastErrorScript=
()=>this.kc("runtime","go-to-last-error-script"))}async df(c,g){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;this.Lb=C.map(q=>new q(this));this.rd();var l=c.Pa.map(q=>"string"===typeof q?(new URL(q,this.D)).toString():q);Array.isArray(c.$c)&&l.unshift(...c.$c);l=await Promise.all(l.map(q=>this.xc(q,this.da)));await Promise.all(l.map(q=>b(q,this.da)));const n=self.C3_ProjectScriptsStatus;if("module"===this.da){l=c.ae;const q=
c.qb;for(let [t,r]of q)if(r||(r=t),t===l)try{r=await this.xc(r,this.da),await b(r,this.da),"preview"!==this.L||n[t]||this.Bd(t,"main script did not run to completion")}catch(z){this.Bd(t,z)}else if("scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r=await this.xc(r,this.da),await b(r,this.da)}else if(c.qb&&0<c.qb.length)try{if(await Promise.all(c.qb.map(q=>b(q[1],this.da))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Cd(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",
q);self.setTimeout(()=>this.Cd(n),100);return}"preview"===this.L&&"object"!==typeof self.Ig.Kg?(this.Ua(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.sd(c),{isInWorker:!1,messagePort:g,canvas:this.J,runOnStartupFunctions:H}),this.vd(),this.Ha=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ha,
c))}Cd(c){this.Ua();c=`Failed to load project script '${Object.entries(c).filter(g=>!g[1]).map(g=>g[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}Bd(c,g){this.Ua();console.error(`[Preview] Failed to load project main script (${c}): `,g);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}vd(){this.Ua()}Ua(){const c=window.xg;c&&(c.parentElement.removeChild(c),
window.xg=null)}async mf(){const c=await O(this.cb);return{outputPort:c,transferables:[c]}}cf(){if(this.ra)throw Error("not available in worker mode");return this.Ha}kc(c,g,l,n,q){this.pa.postMessage({type:"event",component:c,handler:g,dispatchOpts:n||null,data:l,responseId:null},q)}kd(c,g,l,n,q){const t=F++,r=new Promise((z,R)=>{D.set(t,{resolve:z,reject:R})});this.pa.postMessage({type:"event",component:c,handler:g,dispatchOpts:n||null,data:l,responseId:t},q);return r}["_OnMessageFromRuntime"](c){const g=
c.type;if("event"===g)return this.sf(c);if("result"===g)this.Ff(c);else if("runtime-ready"===g)this.Gf();else if("alert-error"===g)this.Ua(),alert(c.message);else if("creating-runtime"===g)this.vd();else throw Error(`unknown message '${g}'`);}sf(c){const g=c.component,l=c.handler,n=c.data,q=c.responseId;if(c=x.get(g))if(c=c.get(l)){var t=null;try{t=c(n)}catch(r){console.error(`Exception in '${g}' handler '${l}':`,r);null!==q&&this.Eb(q,!1,""+r);return}if(null===q)return t;t&&t.then?t.then(r=>this.Eb(q,
!0,r)).catch(r=>{console.error(`Rejection from '${g}' handler '${l}':`,r);this.Eb(q,!1,""+r)}):this.Eb(q,!0,t)}else console.warn(`[DOM] No handler '${l}' for component '${g}'`);else console.warn(`[DOM] No event handlers for component '${g}'`)}Eb(c,g,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:g,result:l},n)}Ff(c){const g=c.responseId,l=c.isOk;c=c.result;const n=D.get(g);l?n.resolve(c):n.reject(c);D.delete(g)}B(c,g,l){let n=x.get(c);n||(n=new Map,
x.set(c,n));if(n.has(g))throw Error(`[DOM] Component '${c}' already has handler '${g}'`);n.set(g,l)}static $b(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}rd(){for(const c of this.Lb)if("runtime"===c.Wa){this.Ma=c;return}throw Error("cannot find runtime DOM handler");}yf(c){this.kc("debugger","message",c)}Gf(){for(const c of this.Lb)c.ad()}static ic(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Oe(c){this.Ka.push(c);
this.Fc()}Rf(c){c=this.Ka.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ka.splice(c,1);this.Ka.length||this.qc()}Fc(){-1===this.La&&this.Ka.length&&(this.La=requestAnimationFrame(this.vg))}qc(){-1!==this.La&&(cancelAnimationFrame(this.La),this.La=-1)}Cf(){this.La=-1;for(const c of this.Ka)c();this.Fc()}ua(c){this.Ma.ua(c)}Ca(c){this.Ma.Ca(c)}Ec(){this.Ma.Ec()}zb(c){this.Ma.zb(c)}Ae(){return!!v["audio/webm; codecs=opus"]}async og(c){c=await this.kd("runtime","opus-decode",{arrayBuffer:c},
null,[c]);return new Float32Array(c)}ze(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}hd(c){return!this.ze(c)}async xc(c,g){return"cordova"===this.L&&"module"===g&&(c.startsWith("file:")||"file:"===location.protocol&&this.hd(c))?(c.startsWith(this.D)&&(c=c.substr(this.D.length)),c=await this.rb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async lf(c){const g=c.filename;switch(c.as){case "text":return await this.se(g);case "buffer":return await this.rb(g);
default:throw Error("unsupported type");}}dd(c){const g=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(g,q=>{q.file(l,n)},n)})}async se(c){c=await this.dd(c);return await A(c)}rc(){if(u.length&&!(8<=w)){w++;var c=u.shift();this.Ue(c.filename,c.Eg,c.zg)}}rb(c){return new Promise((g,l)=>{u.push({filename:c,Eg:n=>{w--;this.rc();g(n)},zg:n=>{w--;this.rc();l(n)}});this.rc()})}async Ue(c,g,l){try{const n=await this.dd(c),q=await B(n);
g(q)}catch(n){l(n)}}async Te(){const c=[];for(const [g,l]of Object.entries(this.ia))c.push(this.Se(g,l));await Promise.all(c)}async Se(c,g){if("object"===typeof g)this.ia[c]=new Blob([g.str],{type:g.type}),this.Qb[c]=g.str;else{let l=await this.af(g);l||(l=this.We(g));this.ia[c]=l}}async af(c){try{return await (await fetch(c)).blob()}catch(g){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
g),null}}We(c){c=this.Lf(c);return this.Re(c.data,c.Bg)}Lf(c){var g=c.indexOf(",");if(0>g)throw new URIError("expected comma in data: uri");var l=c.substring(g+1);g=c.substring(5,g).split(";");c=g[0]||"";const n=g[2];l="base64"===g[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Bg:c,data:l}}Re(c,g){var l=c.length;let n=l>>2,q=new Uint8Array(l),t=new Uint32Array(q.buffer,0,n),r,z;for(z=r=0;r<n;++r)t[r]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)q[z]=c.charCodeAt(z),++z;return new Blob([q],{type:g})}}}"use strict";
{const k=self.xb;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,c)=>{const g=document.createElement("link");g.onload=()=>h(g);g.onerror=l=>c(l);g.rel=
"stylesheet";g.href=e;document.head.appendChild(g)})}function v(e){return new Promise((h,c)=>{const g=new Image;g.onload=()=>h(g);g.onerror=l=>c(l);g.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((h,c)=>{let g=new FileReader;g.onload=l=>h(l.target.result);g.onerror=l=>c(l);g.readAsText(e)})}async function u(e,h,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var g=await B(e);g=(new DOMParser).parseFromString(g,
"image/svg+xml");const l=g.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),q=l.getAttribute("height");if(!n.includes("%")&&!q.includes("%"))return await A(e)}l.setAttribute("width",h+"px");l.setAttribute("height",c+"px");g=(new XMLSerializer).serializeToString(g);e=new Blob([g],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["canvas",
"body","html"]);function x(e){C.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function D(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,h.height]}};self.C3_RasterSvgImageBlob=async function(e,
h,c,g,l){e=await u(e,h,c);const n=document.createElement("canvas");n.width=g;n.height=l;n.getContext("2d").drawImage(e,0,0,h,c);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function H(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}k.$b(class extends self.sb{constructor(e){super(e,"runtime");this.Md=!0;this.Na=-1;this.Xc="any";this.Dd=this.Ed=!1;this.Rc=this.lb=this.ya=null;e.B("canvas","update-size",g=>
this.Jf(g));e.B("runtime","invoke-download",g=>this.wf(g));e.B("runtime","raster-svg-image",g=>this.Df(g));e.B("runtime","get-svg-image-size",g=>this.uf(g));e.B("runtime","set-target-orientation",g=>this.Hf(g));e.B("runtime","register-sw",()=>this.Ef());e.B("runtime","post-to-debugger",g=>this.xd(g));e.B("runtime","go-to-script",g=>this.xd(g));e.B("runtime","before-start-ticking",()=>this.kf());e.B("runtime","debug-highlight",g=>this.nf(g));e.B("runtime","enable-device-orientation",()=>this.Qe());
e.B("runtime","enable-device-motion",()=>this.Pe());e.B("runtime","add-stylesheet",g=>this.hf(g));e.B("runtime","alert",g=>this.jf(g));e.B("runtime","hide-cordova-splash",()=>this.vf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",g=>{const l=g.target;h.has(l.tagName.toLowerCase())||w(l)||g.preventDefault()});const c=e.J;window.addEventListener("selectstart",x);window.addEventListener("gesturehold",x);c.addEventListener("selectstart",x);c.addEventListener("gesturehold",
x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),c.addEventListener("pointerdown",x)):c.addEventListener("touchstart",x);this.ib=0;window.addEventListener("mousedown",g=>{1===g.button&&g.preventDefault()});window.addEventListener("mousewheel",D,{passive:!1});window.addEventListener("wheel",D,{passive:!1});window.addEventListener("resize",()=>this.Kf());window.addEventListener("fullscreenchange",()=>this.zc());
window.addEventListener("webkitfullscreenchange",()=>this.zc());window.addEventListener("mozfullscreenchange",()=>this.zc());window.addEventListener("fullscreenerror",g=>this.Ac(g));window.addEventListener("webkitfullscreenerror",g=>this.Ac(g));window.addEventListener("mozfullscreenerror",g=>this.Ac(g));e.jc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var g=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));g="textarea"===
g?!0:"input"===g?l.has(n.type.toLowerCase()||"text"):w(n)}else g=!1}g||(document.scrollingElement.scrollTop=0)});this.Ia=new Set;this.Rb=new WeakSet;this.oa=!1}kf(){"cordova"===this.v.L?(document.addEventListener("pause",()=>this.Dc(!0)),document.addEventListener("resume",()=>this.Dc(!1))):document.addEventListener("visibilitychange",()=>this.Dc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}ad(){window.addEventListener("focus",()=>this.Fb("window-focus"));window.addEventListener("blur",
()=>{this.Fb("window-blur",{parentHasFocus:H()});this.ib=0});window.addEventListener("keydown",h=>this.wd("keydown",h));window.addEventListener("keyup",h=>this.wd("keyup",h));window.addEventListener("dblclick",h=>this.Bc("dblclick",h,d));window.addEventListener("wheel",h=>this.Af(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.uc(h);this.Ta("pointerdown",h)}),this.v.ra&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.lb=new self.Fe(()=>this.Ze(),
5),this.lb.Hd=!0,window.addEventListener("pointerrawupdate",h=>this.Bf(h))):window.addEventListener("pointermove",h=>this.Ta("pointermove",h)),window.addEventListener("pointerup",h=>this.Ta("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ta("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.uc(h);this.Cc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Cc("pointermove",h)),window.addEventListener("mouseup",h=>this.Cc("pointerup",h)),window.addEventListener("touchstart",
h=>{this.uc(h);this.Db("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Db("pointermove",h)),window.addEventListener("touchend",h=>this.Db("pointerup",h)),window.addEventListener("touchcancel",h=>this.Db("pointercancel",h)));const e=()=>this.Ec();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Fb(e,h){y(this,e,h||null,m)}wa(){return this.v.wa()}va(){return this.v.va()}Kf(){const e=
this.wa(),h=this.va();this.Fb("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio});this.v.jc()&&(-1!==this.Na&&clearTimeout(this.Na),this.yd(e,h,0))}Sf(e,h,c){-1!==this.Na&&clearTimeout(this.Na);this.Na=setTimeout(()=>this.yd(e,h,c),48)}yd(e,h,c){const g=this.wa(),l=this.va();this.Na=-1;g!=e||l!=h?this.Fb("window-resize",{innerWidth:g,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>c&&this.Sf(g,l,c+1)}Hf(e){this.Xc=e.targetOrientation}kg(){const e=this.Xc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",
h)}}zc(){const e=k.ic();e&&"any"!==this.Xc&&this.kg();y(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.wa(),innerHeight:this.va()})}Ac(e){console.warn("[Construct 3] Fullscreen request failed: ",e);y(this,"fullscreenerror",{isFullscreen:k.ic(),innerWidth:this.wa(),innerHeight:this.va()})}Dc(e){e?this.v.qc():this.v.Fc();y(this,"visibilitychange",{hidden:e})}wd(e,h){"Backspace"===h.key&&x(h);const c=b.get(h.code)||h.code;E(this,e,{code:c,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,
ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Af(e){y(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Bc(e,h,c){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},c)}Cc(e,h){if(!a(h)){var c=this.ib;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===
e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:c,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.ib=h.buttons;this.Bc(h.type,h,f)}}Ta(e,h){if(this.lb&&"pointermove"!==e){var c=this.lb;c.ab||(K(c),c.Ob=Date.now())}c=0;"mouse"===h.pointerType&&(c=this.ib);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,
button:h.button,buttons:h.buttons,lastButtons:c,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Bc(c,h,f),this.ib=h.buttons)}Bf(e){this.Rc=e;e=this.lb;if(-1===e.Oa){var h=Date.now(),c=h-e.Ob,g=e.qg;
c>=g&&e.Hd?(e.Ob=h,e.ab=!0,e.Ic(),e.ab=!1):e.Oa=self.setTimeout(e.Zd,Math.max(g-c,4))}}Ze(){this.Ta("pointermove",this.Rc);this.Rc=null}Db(e,h){for(let c=0,g=h.changedTouches.length;c<g;++c){const l=h.changedTouches[c];E(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},d)}}uc(e){window!==window.top&&window.focus();this.ud(e.target)&&document.activeElement&&!this.ud(document.activeElement)&&document.activeElement.blur()}ud(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Qe(){this.Ed||(this.Ed=!0,window.addEventListener("deviceorientation",e=>this.qf(e)),window.addEventListener("deviceorientationabsolute",e=>this.rf(e)))}Pe(){this.Dd||(this.Dd=!0,window.addEventListener("devicemotion",
e=>this.pf(e)))}qf(e){y(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}rf(e){y(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}pf(e){let h=null;var c=e.acceleration;c&&(h={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var g=e.accelerationIncludingGravity;g&&(c={x:g.x||
0,y:g.y||0,z:g.z||0});g=null;const l=e.rotationRate;l&&(g={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});y(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:c,rotationRate:g,interval:e.interval,timeStamp:e.timeStamp},d)}Jf(e){const h=this.v.J;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Md&&(h.style.display="",this.Md=!1)}wf(e){const h=e.url;e=e.filename;const c=document.createElement("a"),
g=document.body;c.textContent=e;c.href=h;c.download=e;g.appendChild(c);c.click();g.removeChild(c)}async Df(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async uf(e){return await self.C3_GetSvgImageSize(e.blob)}async hf(e){await p(e.url)}Ec(){var e=[...this.Ia];this.Ia.clear();if(!this.oa)for(const h of e)(e=h.play())&&
e.catch(()=>{this.Rb.has(h)||this.Ia.add(h)})}ua(e){if("function"!==typeof e.play)throw Error("missing play function");this.Rb.delete(e);let h;try{h=e.play()}catch(c){this.Ia.add(e);return}h&&h.catch(()=>{this.Rb.has(e)||this.Ia.add(e)})}Ca(e){this.Ia.delete(e);this.Rb.add(e)}zb(e){this.oa=!!e}vf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}nf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));
var h=this.ya;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Ef(){window.C3_RegisterSW&&window.C3_RegisterSW()}xd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}ff(e,h){return this.v.kd(this.Wa,"js-invoke-function",{name:e,params:h},void 0,void 0)}jf(e){alert(e.message)}})}"use strict";
async function M(k){if(k.pg)throw Error("already initialised");k.pg=!0;var a=k.Vb.tc("dispatchworker.js");k.Kc=await k.Vb.bc(a,k.D,{name:"DispatchWorker"});a=new MessageChannel;k.Oc=a.port1;k.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);k.Vc=await O(k)}function N(k){return[k.Oc,k.Vc]}
async function O(k){const a=k.Nd.length;var b=k.Vb.tc("jobworker.js");b=await k.Vb.bc(b,k.D,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;k.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);k.Nd.push(b);return f.port1}
self.Be=class{constructor(k){this.Vb=k;this.D=k.D;this.D="preview"===k.L?this.D+"c3/workers/":this.D+k.Wb;this.sg=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Nd=[];this.Vc=this.Oc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.xb({Fg:!0,Gg:"workermain.js",Pa:["scripts/c3runtime.js"],qb:[],ae:"",be:"module",Cg:"scripts/",$c:["box2d.wasm.js"],$d:"html5"}));"use strict";
self.xb.$b(class extends self.sb{constructor(k){super(k,"mouse");G(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const k=180/Math.PI;self.ea=class extends self.sb{constructor(a){super(a,"audio");this.Kb=this.f=null;this.Mb=this.Nc=!1;this.qa=()=>this.lg();this.aa=[];this.C=[];this.ha=null;this.Od="";this.Pd=-1;this.kb=new Map;this.Sc=1;this.oa=!1;this.Yc=0;this.Yb=1;this.Lc=0;this.Rd="HRTF";this.Id="inverse";this.Sd=600;this.Qd=1E4;this.Ud=1;this.Kd=this.Wc=!1;this.Xd=this.v.Ae();this.ba=new Map;this.Fa=new Set;this.Pc=!1;this.Tc="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.zf(b,d);this.Jb=null;
self.C3Audio_GetOutputStream=()=>this.tf();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.Ve(b)],["play",b=>this.Mf(b)],["stop",b=>this.ig(b)],["stop-all",()=>this.jg()],["set-paused",b=>this.bg(b)],["set-volume",b=>this.gg(b)],["fade-volume",b=>this.$e(b)],["set-master-volume",b=>this.$f(b)],["set-muted",b=>this.ag(b)],["set-silent",b=>this.dg(b)],["set-looping",b=>this.Zf(b)],["set-playback-rate",b=>this.cg(b)],["seek",b=>this.Tf(b)],["preload",b=>this.Nf(b)],["unload",b=>
this.mg(b)],["unload-all",()=>this.ng()],["set-suspended",b=>this.eg(b)],["add-effect",b=>this.pd(b)],["set-effect-param",b=>this.Wf(b)],["remove-effects",b=>this.Pf(b)],["tick",b=>this.If(b)],["load-state",b=>this.xf(b)]])}async Ve(a){a.isiOSCordova&&(this.Wc=!0);this.Yc=a.timeScaleMode;this.Rd=["equalpower","HRTF","soundfield"][a.panningModel];this.Id=["linear","inverse","exponential"][a.distanceModel];this.Sd=a.refDistance;this.Qd=a.maxDistance;this.Ud=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.Xd||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.qd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.qd()};this.Kb=this.f.createGain();this.Kb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.cc();try{await Promise.all(a.preloadList.map(d=>this.Bb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}qd(){this.Mb||(this.Nc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Mb=!0)}Xe(){this.Mb&&(this.Nc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Mb=!1)}lg(){if(!this.Nc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Xe()}}W(){return this.f}cc(){return this.f.currentTime}sa(){return this.Kb}fd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.sa()}ce(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.Yf(d.length);b.fg(a);d.push(b);this.Ad(a)}Ad(a){let b=this.sa();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let f=0,m=d.length;f<m;++f){const p=d[f];f+1===m?p.S(this.sa()):p.S(d[f+1].P())}}for(const f of this.ma(a))f.Ge(b);this.za&&this.Tc===a&&(this.za.disconnect(),this.za.connect(b))}ub(){return this.Sc}vb(){return this.oa}Xf(){this.Kd=!0}ue(a,b){return b?this.v.og(a).then(d=>{const f=this.f.createBuffer(1,d.length,48E3);f.getChannelData(0).set(d);return f}):
new Promise((d,f)=>{this.f.decodeAudioData(a,d,f)})}ua(a){this.v.ua(a)}Ca(a){this.v.Ca(a)}ld(a){let b=0;for(let d=0,f=this.C.length;d<f;++d){const m=this.C[d];this.C[b]=m;m.K===a?m.c():++b}this.C.length=b}He(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const f=this.aa[b];this.aa[a]=f;f.ta()?f.c():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.C)self.ea.ve(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Bb(a,b,d,f,m){for(const p of this.aa)if(p.Ra()===b)return await P(p),
p;if(m)return null;f&&(this.Wc||this.Kd)&&this.He();m="audio/webm; codecs=opus"===d&&!this.Xd;f&&m&&this.Xf();a=!f||this.Wc||m?new self.qe(this,a,b,d,f,m):new self.oe(this,a,b,d,f);this.aa.push(a);await P(a);return a}async sc(a,b,d,f,m){for(const p of this.C)if(p.Ra()===b&&(p.ac()||m))return p.Je(f),p;a=await this.Bb(a,b,d,m);f="html5"===a.Gc?new self.pe(a.i,a,f):new self.re(a.i,a,f);this.C.push(f);return f}Ne(a){let b=this.kb.get(a);if(!b){let d=null;b={Zc:0,promise:new Promise(f=>d=f),resolve:d};
this.kb.set(a,b)}b.Zc++}Qf(a){const b=this.kb.get(a);if(!b)throw Error("expected pending tag");b.Zc--;0===b.Zc&&(b.resolve(),this.kb.delete(a))}pc(a){a||(a=this.Od);return(a=this.kb.get(a))?a.promise:Promise.resolve()}Cb(){if(0<this.Fa.size)J(this);else for(const a of this.C)if(a.gd()){J(this);break}}Da(){for(var a of this.Fa)a.Da();a=this.cc();for(var b of this.C)b.Da(a);b=this.C.filter(d=>d.gd()).map(d=>d.Qa());y(this,"state",{tickCount:this.Pd,audioInstances:b,analysers:[...this.Fa].map(d=>d.xe())});
0===b.length&&0===this.Fa.size&&this.Nb&&(this.v.Rf(this.Yd),this.Nb=!1)}lc(a,b,d){y(this,"trigger",{type:a,tag:b,aiid:d})}async Mf(a){const b=a.originalUrl,d=a.url,f=a.type,m=a.isMusic,p=a.tag,v=a.isLooping,A=a.vol,B=a.pos,u=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Od=p;this.Ne(p);try{this.ha=await this.sc(b,d,f,p,m),u?(this.ha.yb(!0),this.ha.Ie(u.x,
u.y,u.angle,u.innerAngle,u.outerAngle,u.outerGain),u.hasOwnProperty("uid")&&this.ha.Ke(u.uid)):this.ha.yb(!1),this.ha.Play(v,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Qf(p)}J(this)}ig(a){a=a.tag;for(const b of this.ma(a))b.na()}jg(){for(const a of this.C)a.na()}bg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Sa():d.wb();this.Cb()}gg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Ab(a)}async $e(a){const b=a.tag,d=a.vol,
f=a.duration;a=a.stopOnEnd;await this.pc(b);for(const m of this.ma(b))m.we(d,f,a);this.Cb()}$f(a){this.Sc=a.vol;for(const b of this.C)b.Hb()}ag(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.md(a)}dg(a){this.oa=a.isSilent;this.v.zb(this.oa);for(const b of this.C)b.Gb()}Zf(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.nc(a)}async cg(a){const b=a.tag;a=a.rate;await this.pc(b);for(const d of this.ma(b))d.od(a)}async Tf(a){const b=a.tag;a=a.pos;await this.pc(b);for(const d of this.ma(b))d.mc(a)}async Nf(a){const b=
a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.sc(b,d,f,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async mg(a){if(a=await this.Bb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}ng(){for(const a of this.aa)a.c();this.aa.length=0}eg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.oc(a);a&&this.f.suspend&&this.f.suspend()}If(a){this.Yb=a.timeScale;this.Lc=a.gameTime;this.Pd=a.tickCount;if(0!==
this.Yc)for(var b of this.C)b.Ea();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.C)f.ga===a&&f.nd(d.x,d.y,d.angle)}}async pd(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.ie(this,...f);else if("delay"===b)f=new self.ge(this,...f);else if("convolution"===b){b=null;try{b=await this.Bb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}f=new self.fe(this,b.$,...f);f.Uf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.je(this,...f);else if("phaser"===b)f=new self.le(this,...f);else if("gain"===b)f=new self.ke(this,...f);else if("tremolo"===b)f=new self.ne(this,...f);else if("ringmod"===b)f=new self.me(this,...f);else if("distortion"===b)f=new self.he(this,...f);else if("compressor"===b)f=new self.ee(this,...f);else if("analyser"===b)f=new self.de(this,...f);else throw Error("invalid effect type");this.ce(d,
f);this.zd()}Wf(a){const b=a.index,d=a.param,f=a.value,m=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,m,p),this.zd())}Pf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Ad(a)}}Me(a){this.Fa.add(a);this.Cb()}Of(a){this.Fa.delete(a)}zd(){this.Pc||(this.Pc=!0,Promise.resolve().then(()=>this.Ye()))}Ye(){const a={};for(const [b,d]of this.ba)a[b]=d.map(f=>f.Qa());y(this,"fxstate",{fxstate:a});this.Pc=!1}async xf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.C)d.ta()&&1===b||(d.ta()||2!==b)&&d.na();for(const f of this.ba.values())for(const m of f)m.c();this.ba.clear();this.Yb=a.timeScale;this.Lc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.v.zb(this.oa);this.Sc=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(m=>this.pd(m))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.gf(f,b)));this.Cb()}async gf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,f=a.bufferUrl,m=a.bufferType,p=a.isMusic,v=a.tag,A=a.isLooping,B=a.volume,u=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.sc(d,f,m,v,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Ee(a.pan);b.Play(A,B,u,0);a.isPlaying||b.Sa();b.wc(a)}}}zf(a,b){this.za&&this.za.disconnect();this.Tc=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.fd(this.Tc))}tf(){this.Jb||(this.Jb=this.f.createMediaStreamDestination(),
this.Kb.connect(this.Jb));return this.Jb.stream}static ve(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Le(a){return a*k}static te(a){return Math.pow(10,a/20)}static ed(a){return Math.max(Math.min(self.ea.te(a),1),0)}static De(a){return Math.log(a)/Math.log(10)*20}static Ce(a){return self.ea.De(Math.max(Math.min(a,1),0))}static yg(a,b){return 1-Math.exp(-b*a)}};self.xb.$b(self.ea)}"use strict";function P(k){k.Pb||(k.Pb=k.vc());return k.Pb}
self.bd=class{constructor(k,a,b,d,f){this.i=k;this.ug=a;this.Aa=b;this.R=d;this.rg=f;this.Gc="";this.Pb=null}c(){this.Pb=this.i=null}vc(){}W(){return this.i.W()}ec(){return this.ug}Ra(){return this.Aa}dc(){return this.R}ta(){return this.rg}fa(){}};"use strict";
self.oe=class extends self.bd{constructor(k,a,b,d,f){super(k,a,b,d,f);this.Gc="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.eb=this.fb=null;this.I.addEventListener("canplaythrough",()=>!0);this.jb=this.W().createGain();this.hb=null;this.I.addEventListener("canplay",()=>{this.fb&&(this.fb(),this.eb=this.fb=null);!this.hb&&this.I&&(this.hb=this.W().createMediaElementSource(this.I),this.hb.connect(this.jb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,m);this.eb&&(this.eb(m),this.eb=this.fb=null)})}c(){this.i.ld(this);this.jb.disconnect();this.jb=null;this.hb.disconnect();this.hb=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.c()}vc(){return new Promise((k,a)=>{this.fb=k;this.eb=a;this.I.src=this.Aa})}O(){return this.I}fa(){return this.I.duration}};"use strict";
async function Q(k){if(k.xa)return k.xa;var a=k.i.v;if("cordova"===a.L&&a.hd(k.Aa)&&"file:"===location.protocol)k.xa=await a.rb(k.Aa);else{a=await fetch(k.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);k.xa=await a.arrayBuffer()}}async function S(k){if(k.$)return k.$;k.$=await k.i.ue(k.xa,k.tg);k.xa=null}
self.qe=class extends self.bd{constructor(k,a,b,d,f,m){super(k,a,b,d,f);this.Gc="webaudio";this.$=this.xa=null;this.tg=!!m}c(){this.i.ld(this);this.$=this.xa=null;super.c()}async vc(){try{await Q(this),await S(this)}catch(k){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,k)}}fa(){return this.$?this.$.duration:0}};"use strict";
{let k=0;self.cd=class{constructor(a,b,d){this.i=a;this.K=b;this.Z=d;this.Ib=k++;this.M=this.W().createGain();this.M.connect(this.sa());this.A=null;this.bb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.G=!0;this.V=this.la=this.F=!1;this.nb=1;this.Ga=!1;this.Y=1;a=this.i.Yc;this.Qc=1===a&&!this.ta()||2===a;this.Za=this.ga=-1;this.Wd=!1}c(){this.K=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.fd(this.Z)}ub(){return this.i.ub()}tb(){return this.Qc?
this.i.Lc:performance.now()/1E3}ec(){return this.K.ec()}Ra(){return this.K.Ra()}dc(){return this.K.dc()}ta(){return this.K.ta()}Je(a){this.Z=a}T(){}ac(){}IsPlaying(){return!this.G&&!this.F&&!this.T()}gd(){return!this.G&&!this.T()}Ba(){}fa(){return this.K.fa()}Play(){}na(){}Sa(){}wb(){}Ab(a){this.nb=a;this.M.gain.cancelScheduledValues(0);this.Za=-1;this.M.gain.value=this.fc()}we(a,b,d){if(!this.Ga){a*=this.ub();var f=this.M.gain;f.cancelScheduledValues(0);var m=this.i.cc();b=m+b;f.setValueAtTime(f.value,
m);f.linearRampToValueAtTime(a,b);this.nb=a;this.Za=b;this.Wd=d}}Hb(){this.Ab(this.nb)}Da(a){-1!==this.Za&&a>=this.Za&&(this.Za=-1,this.Wd&&this.na(),this.i.lc("fade-ended",this.Z,this.Ib))}fc(){const a=this.nb*this.ub();return isFinite(a)?a:0}md(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Gb())}vb(){return this.i.vb()}Gb(){}nc(){}od(a){this.Y!==a&&(this.Y=a,this.Ea())}Ea(){}mc(){}oc(){}yb(a){a=!!a;this.bb!==a&&((this.bb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Rd,this.A.distanceModel=
this.i.Id,this.A.refDistance=this.i.Sd,this.A.maxDistance=this.i.Qd,this.A.rolloffFactor=this.i.Ud),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.sa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Ie(a,b,d,f,m,p){this.bb&&(this.nd(a,b,d),a=self.ea.Le,this.A.coneInnerAngle=a(f),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}nd(a,b,d){this.bb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.A.setPosition(...this.ka),
this.A.setOrientation(...this.ja))}Ke(a){this.ga=a}hc(){}Ge(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Qa(){return{aiid:this.Ib,tag:this.Z,duration:this.fa(),volume:this.nb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.Y,uid:this.ga,bufferOriginalUrl:this.ec(),bufferUrl:"",bufferType:this.dc(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.hc(),pan:this.ye()}}wc(a){this.od(a.playbackRate);this.md(a.isMuted)}ye(){if(!this.A)return null;const a=
this.A;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Ee(a){if(a){this.yb(!0);a=this.A;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.yb(!1)}}}"use strict";
self.pe=class extends self.cd{constructor(k,a,b){super(k,a,b);this.K.jb.connect(this.M);this.K.onended=()=>this.yc()}c(){this.na();this.K.jb.disconnect();super.c()}O(){return this.K.O()}yc(){this.G=!0;this.ga=-1;this.i.lc("ended",this.Z,this.Ib)}T(){return this.O().ended}ac(){return this.G?!0:this.T()}Ba(k){let a=this.O().currentTime;k&&(a*=this.Y);this.V||(a=Math.min(a,this.fa()));return a}Play(k,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==k&&(d.loop=k);this.Ab(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.K.Ra()}' to position '${b}': `,f)}this.i.ua(d);this.F=this.G=!1;this.V=k;this.Y=1}na(){const k=this.O();k.paused||k.pause();this.i.Ca(k);this.G=!0;this.F=!1;this.ga=-1}Sa(){if(!(this.F||this.G||this.T())){var k=this.O();k.paused||k.pause();this.i.Ca(k);this.F=!0}}wb(){!this.F||this.G||this.T()||(this.i.ua(this.O()),this.F=!1)}Gb(){this.O().muted=this.Ga||this.vb()}nc(k){k=!!k;
this.V!==k&&(this.V=k,this.O().loop=k)}Ea(){let k=this.Y;this.Qc&&(k*=this.i.Yb);try{this.O().playbackRate=k}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${k}':`,a)}}mc(k){if(!this.G&&!this.T())try{this.O().currentTime=k}catch(a){console.warn(`[Construct 3] Error seeking audio to '${k}': `,a)}}hc(){return this.Ba()}oc(k){k?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.ua(this.O()),this.la=!1)}};"use strict";
function T(k){k.j&&k.j.disconnect();k.j=null;k.Va=null}
self.re=class extends self.cd{constructor(k,a,b){super(k,a,b);this.j=null;this.Sb=d=>this.yc(d);this.Mc=!0;this.Va=null;this.N=this.Xb=0;this.Uc=1}c(){this.na();T(this);this.Sb=null;super.c()}yc(k){this.F||this.la||k.target!==this.Va||(this.G=this.Mc=!0,this.ga=-1,T(this),this.i.lc("ended",this.Z,this.Ib))}T(){return!this.G&&this.j&&this.j.loop||this.F?!1:this.Mc}ac(){return!this.j||this.G?!0:this.T()}Ba(k){let a;a=this.F?this.N:this.tb()-this.Xb;k&&(a*=this.Y);this.V||(a=Math.min(a,this.fa()));return a}Play(k,
a,b,d){this.Uc=1;this.Ab(a);T(this);this.j=this.W().createBufferSource();this.j.buffer=this.K.$;this.j.connect(this.M);this.Va=this.j;this.j.onended=this.Sb;this.j.loop=k;this.j.start(d,b);this.F=this.G=this.Mc=!1;this.V=k;this.Y=1;this.Xb=this.tb()-b}na(){if(this.j)try{this.j.stop(0)}catch(k){}this.G=!0;this.F=!1;this.ga=-1}Sa(){this.F||this.G||this.T()||(this.N=this.Ba(!0),this.V&&(this.N%=this.fa()),this.F=!0,this.j.stop(0))}wb(){!this.F||this.G||this.T()||(T(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.K.$,this.j.connect(this.M),this.Va=this.j,this.j.onended=this.Sb,this.j.loop=this.V,this.Hb(),this.Ea(),this.Xb=this.tb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.F=!1)}fc(){return super.fc()*this.Uc}Gb(){this.Uc=this.Ga||this.vb()?0:1;this.Hb()}nc(k){k=!!k;this.V!==k&&(this.V=k,this.j&&(this.j.loop=k))}Ea(){let k=this.Y;this.Qc&&(k*=this.i.Yb);this.j&&(this.j.playbackRate.value=k)}mc(k){this.G||this.T()||(this.F?this.N=k:(this.Sa(),this.N=k,this.wb()))}hc(){return this.N}oc(k){k?
this.IsPlaying()?(this.la=!0,this.N=this.Ba(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(T(this),this.j=this.W().createBufferSource(),this.j.buffer=this.K.$,this.j.connect(this.M),this.Va=this.j,this.j.onended=this.Sb,this.j.loop=this.V,this.Hb(),this.Ea(),this.Xb=this.tb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.la=!1)}wc(k){super.wc(k);this.N=k.resumePosition}};"use strict";
{class k{constructor(a){this.i=a;this.f=a.W();this.Ld=-1;this.R=this.Z="";this.g=null}c(){this.f=null}Yf(a){this.Ld=a}fg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var m=this.f.currentTime;f+=m;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,f)}}}Qa(){return{type:this.R,tag:this.Z,params:this.g}}}
self.ie=class extends k{constructor(a,b,d,f,m,p,v){super(a);this.R="filter";this.g=[b,d,f,m,p,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=f;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,f)}}};self.ge=class extends k{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.gb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Ya=this.o();this.Ya.gain.value=d;this.l.connect(this.gb);this.l.connect(this.a);this.gb.connect(this.b);this.gb.connect(this.U);this.U.connect(this.Ya);this.Ya.connect(this.gb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.gb.disconnect();this.U.disconnect();this.Ya.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){const m=self.ea.ed;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=m(b);this.m(this.Ya.gain,m(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.fe=class extends k{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Gd=this.Fd="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Xa=this.f.createConvolver();this.Xa.normalize=d;this.Xa.buffer=b;this.l.connect(this.Xa);this.l.connect(this.a);this.Xa.connect(this.b)}c(){this.l.disconnect();this.Xa.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}Uf(a,b){this.Fd=a;this.Gd=b}Qa(){const a=
super.Qa();a.bufferOriginalUrl=this.Fd;a.bufferUrl="";a.bufferType=this.Gd;return a}};self.je=class extends k{constructor(a,b,d,f,m,p){super(a);this.R="flanger";this.g=[b,d,f,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.$a=this.o();this.$a.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.H=this.o();this.H.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.$a);this.$a.connect(this.U);this.s.connect(this.H);this.H.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();this.$a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.$a.gain,b/100,d,f)}}};self.le=class extends k{constructor(a,b,d,f,m,p,v){super(a);this.R="phaser";this.g=[b,d,f,m,p,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=p;this.H=this.o();this.H.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.H);this.H.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.H.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,f)}}};self.ke=class extends k{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){const m=self.ea.ed;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,f)}}};self.ne=class extends k{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.H=this.o();this.H.gain.value=d/2;this.s.connect(this.H);this.H.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.H.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.H.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.me=class extends k{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.mb=this.o();this.mb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.mb.gain);this.s.start(0);this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.mb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,f);
this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.he=class extends k{constructor(a,b,d,f,m,p){super(a);this.R="distortion";this.g=[b,d,f,m,p];this.l=this.o();this.Ub=this.o();this.Tb=this.o();this.Vf(f,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.Zb=this.f.createWaveShaper();this.Jc=new Float32Array(65536);this.bf(b,d);this.Zb.curve=this.Jc;this.l.connect(this.Ub);this.l.connect(this.a);this.Ub.connect(this.Zb);this.Zb.connect(this.Tb);
this.Tb.connect(this.b)}c(){this.l.disconnect();this.Ub.disconnect();this.Zb.disconnect();this.Tb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Vf(a,b){.01>a&&(a=.01);this.Ub.gain.value=a;this.Tb.gain.value=Math.pow(1/a,.6)*b}bf(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.hg(f,a,b);this.Jc[32768+d]=f;this.Jc[32768-d-1]=-f}}hg(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.ea.yg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.ee=class extends k{constructor(a,b,d,f,m,p){super(a);this.R="compressor";this.g=[b,d,f,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.de=class extends k{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Jd=new Float32Array(this.h.frequencyBinCount);this.Vd=new Uint8Array(b);this.Td=this.Ja=0;this.i.Me(this)}c(){this.i.Of(this);this.h.disconnect();super.c()}Da(){this.h.getFloatFrequencyData(this.Jd);this.h.getByteTimeDomainData(this.Vd);const a=this.h.fftSize;let b=this.Ja=0;for(var d=0;d<a;++d){let f=(this.Vd[d]-128)/128;0>f&&(f=-f);
this.Ja<f&&(this.Ja=f);b+=f*f}d=self.ea.Ce;this.Ja=d(this.Ja);this.Td=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}xe(){return{tag:this.Z,index:this.Ld,peak:this.Ja,rms:this.Td,binCount:this.h.frequencyBinCount,freqBins:this.Jd}}}};
